config/routes.rb
Rails.application.routes.draw do

  resources :user_instruments
  resources :instruments
  resources :musician_genres
  resources :genres
  resources :locations
  resources :testimonial_links
  devise_for :users

  
  
  root "users#index"
  get "/users" => "users#index"
  
  get ":username" => "users#show", as: :user

  post "/:username/request_form" => "users#email_request"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/musician_genre.rb
# == Schema Information
#
# Table name: musician_genres
#
#  id         :bigint           not null, primary key
#  user_id    :bigint           not null
#  genre_id   :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class MusicianGenre < ApplicationRecord
  belongs_to :user
  belongs_to :genre
end

app/controllers/musician_genres_controller.rb
class MusicianGenresController < ApplicationController
  before_action :set_musician_genre, only: %i[ show edit update destroy ]

  # GET /musician_genres or /musician_genres.json
  def index
    @q = User.ransack(params[:q])
    @users = @q.result(:distinct => true).includes(:genres)
    # @musician_genres = MusicianGenre.all
    # @users = User.all
  end

  # GET /musician_genres/1 or /musician_genres/1.json
  def show
  end

  # GET /musician_genres/new
  def new
    @musician_genre = MusicianGenre.new
  end

  # GET /musician_genres/1/edit
  def edit
  end

  # POST /musician_genres or /musician_genres.json
  def create
    @musician_genre = MusicianGenre.new(musician_genre_params)

    respond_to do |format|
      if @musician_genre.save
        format.html { redirect_to musician_genre_url(@musician_genre), notice: "Musician genre was successfully created." }
        format.json { render :show, status: :created, location: @musician_genre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @musician_genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musician_genres/1 or /musician_genres/1.json
  def update
    respond_to do |format|
      if @musician_genre.update(musician_genre_params)
        format.html { redirect_to musician_genre_url(@musician_genre), notice: "Musician genre was successfully updated." }
        format.json { render :show, status: :ok, location: @musician_genre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @musician_genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musician_genres/1 or /musician_genres/1.json
  def destroy
    @musician_genre.destroy

    respond_to do |format|
      format.html { redirect_to musician_genres_url, notice: "Musician genre was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_musician_genre
      @musician_genre = MusicianGenre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def musician_genre_params
      params.require(:musician_genre).permit(:user_id, :genre_id)
    end
end

app/helpers/musician_genres_helper.rb
module MusicianGenresHelper
end

app/views/musician_genres/_form.html.erb
<%= form_with(model: musician_genre) do |form| %>
  <% if musician_genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(musician_genre.errors.count, "error") %> prohibited this musician_genre from being saved:</h2>

      <ul>
        <% musician_genre.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :genre_id %>
    <%= form.text_field :genre_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/musician_genres/edit.html.erb
<h1>Editing Musician Genre</h1>

<%= render 'form', musician_genre: @musician_genre %>

<%= link_to 'Show', @musician_genre %> |
<%= link_to 'Back', musician_genres_path %>

app/views/musician_genres/index.html.erb
<div class="container pb-5">
  
  <h1>Teachers By Genres</h1>
  
  <form class="border rounded border-white border-bottom-0 p-4 my-4">
    <%= search_form_for @q do |f| %>
      <p class="fw-bold fs-4" >Narrow results:</p>
  
  
      <div class="mb-2">
        <%= f.label :genres_name_eq, "Search by genre", class: "form-label" %>
        <%= f.select :genres_name_eq, options_from_collection_for_select(Genre.all, :name, :name, @q.genres_name_eq), { :include_blank => true }, class: "form-control form-select" %>
      </div>
  
  
      <%= f.submit class: "btn btn-primary mt-2 mr-3" %>
  
      <%= link_to 'Clear filters', musician_genres_path, class: "ms-3"%>
    <% end %>
  </form>
  
    <% @users.each do |user| %>
      <div class="card mb-4">
        <div class="row g-0">
          <div class="col-md-4">
            <%= image_tag "#{user.avatar_url}", class: "img-fluid rounded-start" %>
          </div>
          <div class="col-md-8">
            <div class="card-header d-flex justify-content-around">
              <h4 class="card-title fs-2"><%= user.username.capitalize%></h4>
              <p class="card-text">
                <span class="text-dark fw-semibold fs-5">Location: </span><%= user.location.location_name %>
              </p>
            </div>
            <div class="card-body">
              <div class="h5">
                <% user.instruments.each do |instrument| %>
                          <span><%= instrument.name %></span>
                      <% end  %>
                      <span class="pt-4">Teacher </span>
              </div>
              <p class="card-text mt-3"><span class="text-dark fw-semibold fs-5">Genre:</span>
                <% user.genres.each do |genre| %>
                  <span><%= user.genres.last != genre ? "#{genre.name}," : genre.name %></span>
                <% end %>
              </p>
              <div class="mt-3">
                <p class="card-text"><span class="text-dark fw-semibold fs-5">About me: </span><%= user.teacher_bio %></p>
              </div>
            <p class="card-text mt-3">
              <%= link_to 'Show', user_path(user.username), class: "btn btn-primary" %>
            </p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  
</div>

app/views/musician_genres/new.html.erb
<h1>New Musician Genre</h1>

<%= render 'form', musician_genre: @musician_genre %>

<%= link_to 'Back', musician_genres_path %>

app/views/musician_genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @musician_genre.user_id %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @musician_genre.genre_id %>
</p>
<% if current_user == @musician_genre.user %>
  
<%= link_to 'Edit', edit_musician_genre_path(@musician_genre) %> |
<%= link_to 'Destroy', @musician_genre, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', musician_genres_path %>