config/routes.rb
Rails.application.routes.draw do

  resources :user_instruments
  resources :instruments
  resources :musician_genres
  resources :genres
  resources :locations
  resources :testimonial_links
  devise_for :users

  
  
  root "users#index"
  get "/users" => "users#index"
  
  get ":username" => "users#show", as: :user

  post "/:username/request_form" => "users#email_request"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :citext           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  location_id            :integer
#  teacher_bio            :text
#  lesson_schedule        :text
#  years_teached          :integer          default(0)
#  avatar_url             :string
#  lesson_pricing         :float
#  student_bio            :text
#  username               :citext
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
         
  belongs_to :location

  has_many :musician_genres, dependent: :destroy
  has_many :testimonial_links

  has_many :user_instruments, foreign_key: "musician_id"
  has_many :genres, through: :musician_genres

  has_many :instruments, through: :user_instruments, source: :instrument, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @q = User.ransack(params[:q])
    @users = @q.result(:distinct => true).includes(:genres, :location, :instruments)
    # @users = User.all.order({ :username => :asc }) 
  end

  def show
    @user = User.find_by!(username: params.fetch(:username))
  end

  def email_request
    @user = User.find_by!(username: params.fetch(:username))
    sender_email = params.fetch(:sender_address)
    recipient_email = params.fetch(:recipient_address)
    message_subject = params.fetch(:subject)
    message_body = params.fetch(:body)

    mg_key = ENV.fetch("MAILGUN_API_KEY")
    mg_sending_domain = ENV.fetch("MAILGUN_SENDING_DOMAIN")
    personal_email = ENV.fetch("PERSONAL_EMAIL")
    mg_client = Mailgun::Client.new(mg_key)

    email_info = {
      :from => sender_email,
      :to => personal_email,
      :subject => message_subject,
      :text => message_body
    }

    mg_client.send_message(mg_sending_domain, email_info)

    redirect_to user_path(@user.username)
  end
end

app/views/users/_request_form.html.erb
<div class="container mb-5 border border-info rounded p-4">
  <h2 class="text-info">Request a Lesson!</h2>
  
  <%= form_with url: "/#{@user.username}/request_form", method: :post, class: "p-3" do |form| %>
  
    <div class="form-group mb-3">
      <%= form.label :sender_address, "Enter your email address:", class: "form-label" %>
      <%= form.email_field :sender_address, placeholder: "john_smith@example.com", class: "form-control" %>
    </div>
  
    <div class="form-group">
      <%= form.hidden_field :recipient_address, value: @user.email %>
    </div>
  
    <div class="form-group mb-3">
      <%= form.label :subject, "Subject:", class: "form-label" %>
      <%= form.text_field :subject, placeholder: "Lesson Request", class: "form-control"  %>
    </div>
  
    <div class="form-group mb-3">
      <%= form.label :body, "Message body:", class: "form-label" %>
      <%= form.text_area :body, rows: 3, placeholder: "Type your request here...", class: "form-control" %>
    </div>
  
    <%= form.button "Send request", class: "mt-3 btn btn-primary" %>
  
  <% end %>
</div>

app/views/users/index.html.erb
<div class="pb-5">
  
  <h1 class="">All Teachers</h1>
  
  <form class="border rounded border-white border-bottom-0 p-4 my-4">
    <%= search_form_for @q do |f| %>
      <p class="fw-bold fs-4">Narrow results:</p>
  
      <%# <div> %>
        <%# <%= f.label :instruments_name_cont, "Search by instrument" %>
        <%# <%= f.text_field :instruments_name_cont, :placeholder => "Enter a few characters" %>
      <%# </div> %>
  
      <div class="mb-2">
        <%= f.label :instruments_name_eq, "Search by instrument", class: "form-label" %>
        <%= f.select :instruments_name_eq, options_from_collection_for_select(Instrument.all, :name, :name, @q.instruments_name_eq), { :include_blank => true }, class: "form-control form-select" %>
      </div>
  
  
      <%# <div> %>
        <%# <%= f.label :genres_name_cont, "Search by genre" %>
        <%# <%= f.text_field :genres_name_cont, :placeholder => "Classical" %>
      <%# </div> %>
  
      <div class="mb-2">
        <%= f.label :genres_name_eq, "Search by genre", class: "form-label" %>
        <%= f.select :genres_name_eq, options_from_collection_for_select(Genre.all, :name, :name, @q.genres_name_eq), { :include_blank => true }, class: "form-control form-select" %>
      </div>
  
      <div class="mb-2">
        <%= f.label :location_location_name_cont, "Search by location", class: "form-label" %>
        <%= f.text_field :location_location_name_cont, :placeholder => "i.e Chicago", class: "form-control" %>
      </div>
  
      <%= f.submit class: "btn btn-primary mt-2 mr-3" %>
  
      <%= link_to 'Clear filters', root_path, class: "ms-3"%>
    <% end %>
  </form>
  
  
  <%# <table> %>
    <%# <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Instrument(s)</th>
        <th>Location</th>
        <th>Lesson Price / 30-min</th>
        <th>Teacher Details</th>
        <th colspan="3"></th>
      </tr>
    </thead> %>
  
    <%# <tbody> %>
    <div class="mb-4">
  
        <% @users.each do |user| %>
  
          <div class="card mb-3" >
            <div class="row g-0">
              <div class="col-md-4" >
                <%= image_tag "#{user.avatar_url}", class: "img-fluid rounded-start" %>
              </div>
              <div class="col-md-8">
                  <div class="card-header d-flex justify-content-around">
                    <h4 class="card-title fs-2"><%= user.username.capitalize %></h4>
                    <p class="card-text"><span class="text-dark fs-5 fw-semibold">Location: </span><%= user.location.location_name %></p>
                  </div>
                <div class="card-body">
                  <% user.instruments.each do |instrument| %>
                      <span class="fs-5 fw-semibold"><%= instrument.name %></span>
                  <% end  %>
                  <span class="pt-4 fs-5 fw-semibold">Teacher </span>
                  <div class="mt-3">
                    <p><span class="text-dark fs-5 fw-semibold">About me: </span><%= user.teacher_bio %></p>
                  </div>
                  <p class="card-text"><span class="text-dark fs-5 fw-semibold">Lesson Price / 30-min: </span><%= user.lesson_pricing.to_s(:currency) %></p>
                  <p class="card-text">
  
                      <%= link_to 'Read more', user_path(user.username), class: "btn btn-primary" %>
  
                  </p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
    </div>
    <%# </tbody> %>
  <%# </table> %>
</div>

app/views/users/show.html.erb
<div class="container-fluid d-flex flex-column">
  <div class="mb-4 d-flex flex-row border border-info rounded-pill p-2">
    <div class="d-flex align-items-center">
      <%= image_tag "#{@user.avatar_url}", class: "rounded-circle w-25 p-1 me-4" %>
      <div class="pl-2">
        <h1><%= @user.username.capitalize %></h1>
        <div class="pt-1">
          <h2 class="h4">Email</h2>
          <p><%= @user.email %></p>
        </div>
      </div>
    </div>
    
    <div class="mt-3 d-inline-flex align-items-center justify-content-around">

      <div class="d-flex flex-column align-items-center me-5">
        <h2 class="fs-5 p-2">Instruments</h2>
        <% @user.instruments.each do |instrument| %>
          <p><%= instrument.name %></p>
        <% end %>
      </div>
      
      <div class="d-flex flex-column align-items-center me-5">
        <h2 class="fs-5 p-2 text-nowrap">Years Teached</h2>
        <p class=""><%= @user.years_teached %></p>
      </div>

      <div class="d-flex flex-column align-items-center me-5">
        <h2 class="fs-5 p-2">Location</h2>
        <p><%= @user.location.location_name %></p>
      </div>
    </div>
  </div>
  
  <div class="d-flex flex-column align-items-center mb-4">
    <h2 class="text-info">About Me</h2>
    <p><%= @user.teacher_bio %></p>
  
    <h2 class="mt-3 text-info">Schedule Availibility & Pricing</h2>
    <p class="h4"><span >Available Days: </span><%= @user.lesson_schedule%></p>
    <p class="h4"><span >Rate: </span><%= @user.lesson_pricing.to_s(:currency)%>/ 30-min lesson </p>
  </div>
  
  
  <div class="d-flex flex-column align-items-center mb-5 gx-5">
    <h2 class="text-info">Video Resume</h2>
    <% if current_user == @user %>
      <div>
      <%= link_to "Add New Video", new_testimonial_link_path %>
    </div>
    <% end %>
    <div class="d-inline-flex">
      <% @user.testimonial_links.each do |video| %>
        <div class="m-3">
          <iframe width="380" height="315"
            src="<%= video.link_url %>" >
          </iframe>
        </div>
        <% if current_user == @user %>
          <div>
            <%= link_to "Edit link", edit_testimonial_link_path(video) %>
            <%= link_to "Delete link", testimonial_link_path(video), method: :delete %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  
  <%= render "users/request_form" %>
</div>