config/routes.rb
Rails.application.routes.draw do

  resources :user_instruments
  resources :instruments
  resources :musician_genres
  resources :genres
  resources :locations
  resources :testimonial_links
  devise_for :users

  
  
  root "users#index"
  get "/users" => "users#index"
  
  get ":username" => "users#show", as: :user

  post "/:username/request_form" => "users#email_request"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user_instrument.rb
# == Schema Information
#
# Table name: user_instruments
#
#  id                    :bigint           not null, primary key
#  own_level_id          :bigint           not null
#  min_teaching_level_id :bigint
#  max_teaching_level_id :bigint
#  instrument_id         :bigint           not null
#  musician_id           :bigint           not null
#  years_played          :integer
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#
class UserInstrument < ApplicationRecord
  


  belongs_to :own_level, class_name: "ProficiencyLevel", foreign_key: "own_level_id"
  belongs_to :min_teaching_level, class_name: "ProficiencyLevel", foreign_key: "min_teaching_level_id"
  belongs_to :max_teaching_level, class_name: "ProficiencyLevel", foreign_key: "max_teaching_level_id"
  
  belongs_to :instrument
  belongs_to :musician, class_name: "User", foreign_key: "musician_id"
end

app/controllers/user_instruments_controller.rb
class UserInstrumentsController < ApplicationController
  before_action :set_user_instrument, only: %i[ show edit update destroy ]

  # GET /user_instruments or /user_instruments.json
  def index
    @q = UserInstrument.ransack(params[:q])
    @user_instruments = @q.result
    # @user_instruments = UserInstrument.all
  end

  # GET /user_instruments/1 or /user_instruments/1.json
  def show
  end

  # GET /user_instruments/new
  def new
    @user_instrument = UserInstrument.new
  end

  # GET /user_instruments/1/edit
  def edit
  end

  # POST /user_instruments or /user_instruments.json
  def create
    @user_instrument = UserInstrument.new(user_instrument_params)

    respond_to do |format|
      if @user_instrument.save
        format.html { redirect_to user_instrument_url(@user_instrument), notice: "User instrument was successfully created." }
        format.json { render :show, status: :created, location: @user_instrument }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_instruments/1 or /user_instruments/1.json
  def update
    respond_to do |format|
      if @user_instrument.update(user_instrument_params)
        format.html { redirect_to user_instrument_url(@user_instrument), notice: "User instrument was successfully updated." }
        format.json { render :show, status: :ok, location: @user_instrument }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_instruments/1 or /user_instruments/1.json
  def destroy
    @user_instrument.destroy

    respond_to do |format|
      format.html { redirect_to user_instruments_url, notice: "User instrument was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_instrument
      @user_instrument = UserInstrument.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_instrument_params
      params.require(:user_instrument).permit(:own_level_id, :min_teaching_level_id, :max_teaching_level_id, :instrument_id, :musician_id, :years_played)
    end
end

app/helpers/user_instruments_helper.rb
module UserInstrumentsHelper
end

app/views/user_instruments/_form.html.erb
<%= form_with(model: user_instrument) do |form| %>
  <% if user_instrument.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_instrument.errors.count, "error") %> prohibited this user_instrument from being saved:</h2>

      <ul>
        <% user_instrument.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :own_level_id %>
    <%= form.text_field :own_level_id %>
  </div>

  <div class="field">
    <%= form.label :min_teaching_level_id %>
    <%= form.text_field :min_teaching_level_id %>
  </div>

  <div class="field">
    <%= form.label :max_teaching_level_id %>
    <%= form.text_field :max_teaching_level_id %>
  </div>

  <div class="field">
    <%= form.label :instrument_id %>
    <%= form.text_field :instrument_id %>
  </div>

  <div class="field">
    <%= form.label :musician_id %>
    <%= form.text_field :musician_id %>
  </div>

  <div class="field">
    <%= form.label :years_played %>
    <%= form.number_field :years_played %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_instruments/edit.html.erb
<h1>Editing User Instrument</h1>

<%= render 'form', user_instrument: @user_instrument %>

<%= link_to 'Show', @user_instrument %> |
<%= link_to 'Back', user_instruments_path %>

app/views/user_instruments/index.html.erb
<div class="pb-5">
  
  <h1>Teachers By Instruments</h1>
  
  <form class="border rounded border-white border-bottom-0 p-4 my-4">
    <%= search_form_for @q do |f| %>
      <p class="fw-bold fs-4">Narrow results:</p>
  
      <div class="mb-2">
        <%= f.label :instrument_name_eq, "Search by instrument", class: "form-label" %>
        <%= f.select :instrument_name_eq, options_from_collection_for_select(Instrument.all, :name, :name, @q.instrument_name_eq), { :include_blank => true }, class: "form-control form-select" %>
      </div>
  
      <%= f.submit class: "btn btn-primary" %>
  
      <%= link_to 'Clear filters', user_instruments_path, class: "ms-3"%>
    <% end %>
  </form>
  
  <%# <table>
    <thead>
      <tr>
        <th></th>
        <th>Musician</th>
        <th>Instrument</th>
        <th>Years Played</th>
        <th>Min teaching level</th>
        <th>Max teaching level</th>
        <th>Teacher Details</th>
        <th colspan="3"></th>
      </tr>
    </thead> %>
  
    <%# <tbody> %>
      <% @user_instruments.each do |user| %>
      <div class="card mb-3">
        <div class="row g-0">
          <div class="col-md-4">
            <%= image_tag "#{user.musician.avatar_url}", class: "img-fluid rounded-start" %>
          </div>
          <div class="col-md-8">
            <div class="card-header d-flex justify-content-around">
              <h4 class="card-title fs-2"><%= user.musician.username.capitalize%></h4>
              <p class="card-text">
                <span class="text-dark fs-5 fw-semibold">Location: </span><%= user.musician.location.location_name %>
              </p>
            </div>
            <div class="card-body">
              <div class="fs-5 fw-semibold">
                <% user.musician.instruments.each do |instrument| %>
                          <span><%= instrument.name %></span>
                      <% end  %>
                      <span class="pt-4 fs-5 fw-semibold">Teacher </span>
              </div>
              <p class="card-text mt-3"><span class="text-dark fs-5 fw-semibold">Years Played: </span><%= user.years_played %></p>
              <div class="mt-3">
                <p class="card-text"><span class="text-dark fs-5 fw-semibold">About me: </span><%= user.musician.teacher_bio %></p>
              </div>
            <p class="card-text mt-3">
              <%= link_to 'Show', user_path(user.musician.username), class: "btn btn-primary" %>
            </p>
            </div>
          </div>
        </div>
      </div>
      <% end %>
</div>

app/views/user_instruments/new.html.erb
<h1>New User Instrument</h1>

<%= render 'form', user_instrument: @user_instrument %>

<%= link_to 'Back', user_instruments_path %>

app/views/user_instruments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Own level:</strong>
  <%= @user_instrument.own_level_id %>
</p>

<p>
  <strong>Min teaching level:</strong>
  <%= @user_instrument.min_teaching_level_id %>
</p>

<p>
  <strong>Max teaching level:</strong>
  <%= @user_instrument.max_teaching_level_id %>
</p>

<p>
  <strong>Instrument:</strong>
  <%= @user_instrument.instrument_id %>
</p>

<p>
  <strong>Musician:</strong>
  <%= @user_instrument.musician_id %>
</p>

<p>
  <strong>Years played:</strong>
  <%= @user_instrument.years_played %>
</p>
<% if current_user == @user_instrument.musician %>
  
<%= link_to 'Edit', edit_user_instrument_path(@user_instrument) %> |
<%= link_to 'Destroy', @user_instrument, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', user_instruments_path %>